version: "3.9"
services:
  web:
    build: .
    container_name: lotto_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app             # 코드 핫리로드(개발 편의)
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # 필요시 depends_on 등 추가 가능
